---
title: "kmeans clustering project-group 8"
output: html_document
---

### Authors: Group 8 - Lin Bai, Shanshan Lin, Yinglun Zhang 

### Define function for task 1
```{r}
library(plotly)
library(ClusterR)
task1 <- function(filename, num_of_cluster) {
  # read data
  df <- read.csv(paste0(root, '/datasets/', filename))[,-1]
  if (ncol(df) < 4) {
    print(paste0(filename, ' contains ', ncol(df), ' columns and ', length(unique(df$Class)), ' Classes.'))
    kmeans_temp <- kmeans(df[1:2], length(unique(df$Class)))
    temp <- cbind(df, cluster = kmeans_temp$cluster) ## task 1-1
    ari <- external_validation(temp$Class, temp$cluster, method = 'adjusted_rand_index')
    print(paste0('ARI from External Validation is ', ari)) ## task 1-2
    classplot <- print(plot_ly(df, x = df[,1], y = df[,2], color = ~Class, type =
'scatter', mode = 'markers') %>% layout(title = paste0('Scatter plot by Class, ', filename))) ## task 1-3
    clusterplot <- print(plot_ly(temp[,-3], x = temp[,1], y = temp[,2], color = ~cluster, type =
'scatter', mode = 'markers') %>% layout(title = paste0('Scatter plot by Cluster, ', filename))) ## task 1-4
    
  } else {
    
    print(paste0(filename, ' contains ', ncol(df), ' columns and ', length(unique(df$Class)), ' Classes.'))
    kmeans_temp <- kmeans(df[1:3], length(unique(df$Class))) # exclude class, as it's technically a categorical variable
    temp <- cbind(df, cluster = kmeans_temp$cluster) ## task 1-1
    ari <- external_validation(temp$Class, temp$cluster, method = 'adjusted_rand_index')
    print(paste0('ARI from External Validation is ', ari)) ## task 1-2
    classplot <- print(plot_ly(df, x = df[,1], y = df[,2], z = df[,3], color = ~Class, type =
'scatter3d', mode = 'markers') %>% layout(title = paste0('Scatter plot by Class, ', filename))) ## task 1-3
    clusterplot <- print(plot_ly(temp[,-4], x = temp[,1], y = temp[,2], z = temp[,3], color = ~cluster, type =
'scatter3d', mode = 'markers') %>% layout(title = paste0('Scatter plot by Cluster, ', filename))) ## task 1-4
    
  ### To-do: how to print these plots out efficiently for the sake of this assignment?
  ## 1. save them in a separate file using pdf()/dev.off()?
  ## 2. display them here using print()? it looks extremely confusing. Maybe use titles or is there a better way?
  ## 3. number of clusters k. Some datasets have 1 class whereas others have 8, this is causing unreasonably low ARI for some data. Should k=unique(df$class)? If we use this, ARI=NaN for data8.
  ## 4. The actual label numbers, '1/2/3/4', for each cluster in k means, is different for every run. Detting seed only returns the ARI for that particular occurrence, which does not seem very accurate. For example, for one seed, ARI for data 1 can be 0.3, and for the other, ARI for data 1 can be 0.8, depending on the labels. Seeding this only catches one. What to do with this?
  }
  
}
```

### call the task 1 function
```{r}
library('rstudioapi')
root <- paste0(dirname(rstudioapi::getSourceEditorContext()$path)) # This line gets your working directory automatically. This is so that this will run when we test this in github. Delete it or whatever when we submit.
files <- list.files(paste0(root, '/datasets'), pattern = "*.csv") # automatically gets all .csv files
data_files <- files[-length(files)] # exclude 'World Indicators.csv'. Should not be running k-means on that for task1.
set.seed(1)
for (file in data_files){
  results <- task1(file, 7)
}
```

### sample of what this function above does, for debugging purposes
```{r}
df <- read.csv('datasets/Data8.csv')[,-1] # the first column of all datasets is some useless index thing
kmeans_temp <- kmeans(df[1:2], 1)
temp <- cbind(df, cluster = kmeans_temp$cluster)
### class plot
classplot <- print(plot_ly(df, x = df[,1], y = df[,2], color = ~Class, type =
'scatter', mode = 'markers') %>% layout(title = 'Scatter plot by Class,.csv'))
### cluster plot
plot_ly(temp[,-3], x = temp[,1], y = temp[,2], color = ~cluster, type =
'scatter', mode = 'markers')
```

### task 2
## task 2 only works on one dataset, World Indicators.csv. I personally don't think we need to write this into a function.
```{r}
df <- read.csv(paste0(dirname(rstudioapi::getSourceEditorContext()$path), '/datasets/World Indicators.csv')) # leave this df alone please, so that we don't need to run a read.csv every time. takes forever
df_numerics <- subset(df, select = -c(Region, Country)) ## how do we make sure this is grouping by 'similar countries' and not regions, given that there can't be any categorical variables here?
kmeans_df <- kmeans(df_numerics, 5) # missing values? average of each country/region maybe?
hierachical_df <- hclust(dist(df_numerics), method = 'complete')

```

